"""empty message

Revision ID: 034e6c1c32f5
Revises: 
Create Date: 2024-08-25 13:50:36.627458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034e6c1c32f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teacher_id', table_name='teacher')
    op.drop_index('ix_teacher_name', table_name='teacher')
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_index('ix_teacher_name', 'teacher', ['name'], unique=False)
    op.create_index('ix_teacher_id', 'teacher', ['id'], unique=False)
    # ### end Alembic commands ###
