"""empty message

Revision ID: 371ec1122f3e
Revises: 9c1583e225cd
Create Date: 2024-09-08 15:53:03.733016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371ec1122f3e'
down_revision: Union[str, None] = '9c1583e225cd'
branch_labels: Union[str, Sequence[str], None] 
depends_on: Union[str, Sequence[str], None] 


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('email', sa.String(), nullable=True))
    op.add_column('student', sa.Column('roll', sa.Integer(), nullable=True))
    op.add_column('teacher', sa.Column('email', sa.String(), nullable=True))
    op.add_column('teacher', sa.Column('dept', sa.String(), nullable=True))
    op.add_column('teacher', sa.Column('designation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'designation')
    op.drop_column('teacher', 'dept')
    op.drop_column('teacher', 'email')
    op.drop_column('student', 'roll')
    op.drop_column('student', 'email')
    # ### end Alembic commands ###
