"""empty message

Revision ID: 5592a9a1c5d2
Revises: 371ec1122f3e
Create Date: 2024-09-08 15:54:17.132975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5592a9a1c5d2'
down_revision: Union[str, None] = '371ec1122f3e'
branch_labels: Union[str, Sequence[str], None] 
depends_on: Union[str, Sequence[str], None] 


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
