"""empty message

Revision ID: 5c6506a870af
Revises: 6379dedf0777
Create Date: 2024-09-07 17:41:37.632634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6506a870af'
down_revision: Union[str, None] = '6379dedf0777'
branch_labels: Union[str, Sequence[str], None] 
depends_on: Union[str, Sequence[str], None] 


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'student', 'users', ['id'], ['id'])
    op.create_foreign_key(None, 'teacher', 'users', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    # ### end Alembic commands ###
