"""empty message

Revision ID: 6379dedf0777
Revises: 034e6c1c32f5
Create Date: 2024-09-04 16:51:25.687744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6379dedf0777'
down_revision: Union[str, None] = '034e6c1c32f5'
branch_labels: Union[str, Sequence[str], None] 
depends_on: Union[str, Sequence[str], None] 


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('admin', 'teacher', 'student', name='roleenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'teacher', 'student', name='roleenum'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
