"""empty message

Revision ID: 9c1583e225cd
Revises: 5c6506a870af
Create Date: 2024-09-08 15:42:48.106793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1583e225cd'
down_revision: Union[str, None] = '5c6506a870af'
branch_labels: Union[str, Sequence[str], None] 
depends_on: Union[str, Sequence[str], None] 


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('dept', sa.String(), nullable=True))
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('student', 'dept')
    # ### end Alembic commands ###
